WOERTER = {
    1: ['AUTO', 'NASE', 'HASE', 'TASSE', 'DOSE', 'ROSE', 'SONNE', 'MOND', 'KANNE', 'HAND'],
    2: ['SCHUBLADE', 'TASCHENTUCH', 'REGENBOGEN', 'SANDKASTEN', 'BLUMENTOPF', 'HANDSCHUH', 
        'SCHULBUS', 'APFELBAUM', 'KAUFHAUS', 'TURNSCHUH'],
    3: ['GITARRE', 'TABLETT', 'TRITTLEITER', 'VOEGEL', 'MAEHNE', 'GARTEN', 'PRINZESSIN', 
        'PHYSIK', 'YACHT', 'RHYTHMUS']
}
ALPHABET = list('ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ')
